FIX: CI build issues
Windows cannot execute tests, osx-13 cannot install mono.

diff --git a/.github/workflows/nightly-nuget.yml b/.github/workflows/nightly-nuget.yml
--- a/.github/workflows/nightly-nuget.yml
+++ b/.github/workflows/nightly-nuget.yml
@@ -128,7 +128,7 @@ jobs:
         run: cmake --build --preset ${{ matrix.config.preset }}
 
       - name: Test ${{ matrix.config.preset }}
-        run: ctest --preset ${{ matrix.config.preset }}
+        run: ctest --preset ${{ matrix.config.preset }} --config ${{ matrix.config.configuration }}
 
       - name: Build NuGet package
         run: nuget pack nuget/vanillapdf.runtime.nuspec
@@ -175,8 +175,13 @@ jobs:
 
       - name: Install Mono & NuGet
         run: |
-          brew install mono
-          brew link --overwrite mono
+          # Try installing mono, but continue even if linking fails
+          if ! brew install mono; then
+            echo "Mono installed, but link failed. Forcing overwrite..."
+            brew link --overwrite mono
+          fi
+          
+          # Download and prepare NuGet
           curl -L https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -o nuget.exe
           chmod +x nuget.exe
 
